# Generated by Django 3.0.5 on 2020-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200421_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
